[2023-02-21 11:07:22 +0530] [36700] [DEBUG] Current configuration:
  config: configs/gunicorn/dev.py
  wsgi_app: mailer.wsgi:application
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 2
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: True
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /mnt/InActive/activeProjects/mailer
  daemon: False
  raw_env: []
  pidfile: configs/gunicorn/dev.pid
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: configs/gunicorn/dev.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: configs/gunicorn/dev.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: gunicorn
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f0241eee200>
  on_reload: <function OnReload.on_reload at 0x7f0241eee320>
  when_ready: <function WhenReady.when_ready at 0x7f0241eee440>
  pre_fork: <function Prefork.pre_fork at 0x7f0241eee560>
  post_fork: <function Postfork.post_fork at 0x7f0241eee680>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f0241eee7a0>
  worker_int: <function WorkerInt.worker_int at 0x7f0241eee8c0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f0241eee9e0>
  pre_exec: <function PreExec.pre_exec at 0x7f0241eeeb00>
  pre_request: <function PreRequest.pre_request at 0x7f0241eeec20>
  post_request: <function PostRequest.post_request at 0x7f0241eeecb0>
  child_exit: <function ChildExit.child_exit at 0x7f0241eeedd0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f0241eeeef0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f0241eef010>
  on_exit: <function OnExit.on_exit at 0x7f0241eef130>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-02-21 11:07:22 +0530] [36700] [INFO] Starting gunicorn 20.1.0
[2023-02-21 11:07:22 +0530] [36700] [DEBUG] Arbiter booted
[2023-02-21 11:07:22 +0530] [36700] [INFO] Listening at: http://0.0.0.0:8000 (36700)
[2023-02-21 11:07:22 +0530] [36700] [INFO] Using worker: sync
[2023-02-21 11:07:22 +0530] [36701] [INFO] Booting worker with pid: 36701
[2023-02-21 11:07:22 +0530] [36702] [INFO] Booting worker with pid: 36702
[2023-02-21 11:07:22 +0530] [36700] [DEBUG] 2 workers
PROD SERVER
PROD SERVER
[2023-02-21 11:07:23 +0530] [36701] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/InActive/activeProjects/mailer/mailer/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/InActive/activeProjects/mailer/mailer/settings.py", line 5, in <module>
    from .settings_prod import *
  File "/mnt/InActive/activeProjects/mailer/mailer/settings_prod.py", line 23, in <module>
    SECRET_KEY = os.environ['SERVER_SECRET_KEY']
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'SERVER_SECRET_KEY'
[2023-02-21 11:07:23 +0530] [36702] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/InActive/activeProjects/mailer/mailer/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/InActive/activeProjects/mailer/mailer/settings.py", line 5, in <module>
    from .settings_prod import *
  File "/mnt/InActive/activeProjects/mailer/mailer/settings_prod.py", line 23, in <module>
    SECRET_KEY = os.environ['SERVER_SECRET_KEY']
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'SERVER_SECRET_KEY'
[2023-02-21 11:07:23 +0530] [36701] [INFO] Worker exiting (pid: 36701)
[2023-02-21 11:07:23 +0530] [36702] [INFO] Worker exiting (pid: 36702)
[2023-02-21 11:07:23 +0530] [36700] [WARNING] Worker with pid 36702 was terminated due to signal 15
[2023-02-21 11:07:23 +0530] [36700] [INFO] Shutting down: Master
[2023-02-21 11:07:23 +0530] [36700] [INFO] Reason: Worker failed to boot.
[2023-02-21 11:08:21 +0530] [38802] [DEBUG] Current configuration:
  config: configs/gunicorn/dev.py
  wsgi_app: mailer.wsgi:application
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 2
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: True
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /mnt/InActive/activeProjects/mailer
  daemon: False
  raw_env: []
  pidfile: configs/gunicorn/dev.pid
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: configs/gunicorn/dev.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: configs/gunicorn/dev.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: gunicorn
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f8b70f9e200>
  on_reload: <function OnReload.on_reload at 0x7f8b70f9e320>
  when_ready: <function WhenReady.when_ready at 0x7f8b70f9e440>
  pre_fork: <function Prefork.pre_fork at 0x7f8b70f9e560>
  post_fork: <function Postfork.post_fork at 0x7f8b70f9e680>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f8b70f9e7a0>
  worker_int: <function WorkerInt.worker_int at 0x7f8b70f9e8c0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f8b70f9e9e0>
  pre_exec: <function PreExec.pre_exec at 0x7f8b70f9eb00>
  pre_request: <function PreRequest.pre_request at 0x7f8b70f9ec20>
  post_request: <function PostRequest.post_request at 0x7f8b70f9ecb0>
  child_exit: <function ChildExit.child_exit at 0x7f8b70f9edd0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f8b70f9eef0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f8b70f9f010>
  on_exit: <function OnExit.on_exit at 0x7f8b70f9f130>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-02-21 11:08:21 +0530] [38802] [INFO] Starting gunicorn 20.1.0
[2023-02-21 11:08:21 +0530] [38802] [DEBUG] Arbiter booted
[2023-02-21 11:08:21 +0530] [38802] [INFO] Listening at: http://0.0.0.0:8000 (38802)
[2023-02-21 11:08:21 +0530] [38802] [INFO] Using worker: sync
[2023-02-21 11:08:21 +0530] [38803] [INFO] Booting worker with pid: 38803
[2023-02-21 11:08:21 +0530] [38804] [INFO] Booting worker with pid: 38804
[2023-02-21 11:08:21 +0530] [38802] [DEBUG] 2 workers
PROD SERVER
PROD SERVER
[2023-02-21 05:38:28 +0000] [38804] [DEBUG] worker: SIGWINCH ignored.
[2023-02-21 05:38:28 +0000] [38803] [DEBUG] worker: SIGWINCH ignored.
[2023-02-21 11:08:28 +0530] [38802] [INFO] Handling signal: winch
[2023-02-21 11:08:28 +0530] [38802] [DEBUG] SIGWINCH ignored. Not daemonized
[2023-02-21 05:38:52 +0000] [38803] [DEBUG] GET /api/status
127.0.0.1 - - [21/Feb/2023:05:38:52 +0000] "GET /api/status HTTP/1.1" 200 135 "-" "insomnia/2022.7.5"
[2023-02-21 05:39:02 +0000] [38803] [DEBUG] POST /api/requestcode
127.0.0.1 - - [21/Feb/2023:05:39:02 +0000] "POST /api/requestcode HTTP/1.1" 200 59 "-" "insomnia/2022.7.5"
(554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is Suspend, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is Suspend, ShowTierUpgrade.[EndDiagnosticData] [Hostname=SL2PR02MB3883.apcprd02.prod.outlook.com]')
PYTHON SERVER :: Server error -> Mailing section
[2023-02-21 11:35:08 +0530] [38802] [INFO] Handling signal: int
[2023-02-21 06:05:08 +0000] [38803] [INFO] Worker exiting (pid: 38803)
[2023-02-21 06:05:08 +0000] [38804] [INFO] Worker exiting (pid: 38804)
Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    lock.acquire()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    sys.exit(0)
SystemExit: 0
    sys.exit(0)
SystemExit: 0
[2023-02-21 11:35:08 +0530] [38802] [WARNING] Worker with pid 38804 was terminated due to signal 2
[2023-02-21 11:35:08 +0530] [38802] [WARNING] Worker with pid 38803 was terminated due to signal 2
[2023-02-21 11:35:08 +0530] [38802] [INFO] Shutting down: Master
[2023-02-21 11:45:55 +0530] [114862] [DEBUG] Current configuration:
  config: configs/gunicorn/dev.py
  wsgi_app: mailer.wsgi:application
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 2
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: True
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /mnt/InActive/activeProjects/mailer
  daemon: False
  raw_env: []
  pidfile: configs/gunicorn/dev.pid
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: configs/gunicorn/dev.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: configs/gunicorn/dev.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: gunicorn
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7ff85a5e2200>
  on_reload: <function OnReload.on_reload at 0x7ff85a5e2320>
  when_ready: <function WhenReady.when_ready at 0x7ff85a5e2440>
  pre_fork: <function Prefork.pre_fork at 0x7ff85a5e2560>
  post_fork: <function Postfork.post_fork at 0x7ff85a5e2680>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7ff85a5e27a0>
  worker_int: <function WorkerInt.worker_int at 0x7ff85a5e28c0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7ff85a5e29e0>
  pre_exec: <function PreExec.pre_exec at 0x7ff85a5e2b00>
  pre_request: <function PreRequest.pre_request at 0x7ff85a5e2c20>
  post_request: <function PostRequest.post_request at 0x7ff85a5e2cb0>
  child_exit: <function ChildExit.child_exit at 0x7ff85a5e2dd0>
  worker_exit: <function WorkerExit.worker_exit at 0x7ff85a5e2ef0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7ff85a5e3010>
  on_exit: <function OnExit.on_exit at 0x7ff85a5e3130>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-02-21 11:45:55 +0530] [114862] [INFO] Starting gunicorn 20.1.0
[2023-02-21 11:45:55 +0530] [114862] [DEBUG] Arbiter booted
[2023-02-21 11:45:55 +0530] [114862] [INFO] Listening at: http://0.0.0.0:8000 (114862)
[2023-02-21 11:45:55 +0530] [114862] [INFO] Using worker: sync
[2023-02-21 11:45:55 +0530] [114863] [INFO] Booting worker with pid: 114863
[2023-02-21 11:45:56 +0530] [114864] [INFO] Booting worker with pid: 114864
[2023-02-21 11:45:56 +0530] [114862] [DEBUG] 2 workers
PROD SERVER
PROD SERVER
[2023-02-21 06:16:03 +0000] [114864] [DEBUG] GET /api/status
127.0.0.1 - - [21/Feb/2023:06:16:03 +0000] "GET /api/status HTTP/1.1" 200 135 "-" "insomnia/2022.7.5"
[2023-02-21 06:16:08 +0000] [114864] [DEBUG] POST /api/requestcode
127.0.0.1 - - [21/Feb/2023:06:16:08 +0000] "POST /api/requestcode HTTP/1.1" 200 59 "-" "insomnia/2022.7.5"
(554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is Suspend, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is Suspend, ShowTierUpgrade.[EndDiagnosticData] [Hostname=SL2PR02MB3883.apcprd02.prod.outlook.com]')
PYTHON SERVER :: Server error -> Mailing section
[2023-02-21 11:47:01 +0530] [114862] [INFO] Handling signal: int
[2023-02-21 06:17:01 +0000] [114864] [INFO] Worker exiting (pid: 114864)
[2023-02-21 06:17:01 +0000] [114863] [INFO] Worker exiting (pid: 114863)
Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    lock.acquire()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    sys.exit(0)
SystemExit: 0
    sys.exit(0)
SystemExit: 0
[2023-02-21 11:47:02 +0530] [114862] [INFO] Shutting down: Master
[2023-02-21 11:47:58 +0530] [119061] [DEBUG] Current configuration:
  config: configs/gunicorn/dev.py
  wsgi_app: mailer.wsgi:application
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 2
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: True
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /mnt/InActive/activeProjects/mailer
  daemon: False
  raw_env: []
  pidfile: configs/gunicorn/dev.pid
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: configs/gunicorn/dev.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: configs/gunicorn/dev.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: gunicorn
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f532791a200>
  on_reload: <function OnReload.on_reload at 0x7f532791a320>
  when_ready: <function WhenReady.when_ready at 0x7f532791a440>
  pre_fork: <function Prefork.pre_fork at 0x7f532791a560>
  post_fork: <function Postfork.post_fork at 0x7f532791a680>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f532791a7a0>
  worker_int: <function WorkerInt.worker_int at 0x7f532791a8c0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f532791a9e0>
  pre_exec: <function PreExec.pre_exec at 0x7f532791ab00>
  pre_request: <function PreRequest.pre_request at 0x7f532791ac20>
  post_request: <function PostRequest.post_request at 0x7f532791acb0>
  child_exit: <function ChildExit.child_exit at 0x7f532791add0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f532791aef0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f532791b010>
  on_exit: <function OnExit.on_exit at 0x7f532791b130>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-02-21 11:47:58 +0530] [119061] [INFO] Starting gunicorn 20.1.0
[2023-02-21 11:47:58 +0530] [119061] [DEBUG] Arbiter booted
[2023-02-21 11:47:58 +0530] [119061] [INFO] Listening at: http://0.0.0.0:8000 (119061)
[2023-02-21 11:47:58 +0530] [119061] [INFO] Using worker: sync
[2023-02-21 11:47:58 +0530] [119068] [INFO] Booting worker with pid: 119068
[2023-02-21 11:47:58 +0530] [119069] [INFO] Booting worker with pid: 119069
[2023-02-21 11:47:58 +0530] [119061] [DEBUG] 2 workers
PROD SERVER
PROD SERVER
[2023-02-21 06:18:08 +0000] [119069] [DEBUG] GET /api/status
127.0.0.1 - - [21/Feb/2023:06:18:08 +0000] "GET /api/status HTTP/1.1" 200 135 "-" "insomnia/2022.7.5"
[2023-02-21 06:18:13 +0000] [119069] [DEBUG] POST /api/requestcode
127.0.0.1 - - [21/Feb/2023:06:18:13 +0000] "POST /api/requestcode HTTP/1.1" 200 59 "-" "insomnia/2022.7.5"
PYTHON SERVER :: success sent mail
[2023-02-21 06:18:56 +0000] [119069] [DEBUG] POST /api/requestcode
127.0.0.1 - - [21/Feb/2023:06:18:56 +0000] "POST /api/requestcode HTTP/1.1" 200 59 "-" "insomnia/2022.7.5"
PYTHON SERVER :: success sent mail
[2023-02-21 06:19:39 +0000] [119068] [DEBUG] POST /api/checkcode
127.0.0.1 - - [21/Feb/2023:06:19:39 +0000] "POST /api/checkcode HTTP/1.1" 200 42 "-" "insomnia/2022.7.5"
[2023-02-21 06:20:52 +0000] [119069] [DEBUG] POST /api/requestcode
127.0.0.1 - - [21/Feb/2023:06:20:52 +0000] "POST /api/requestcode HTTP/1.1" 200 59 "-" "insomnia/2022.7.5"
PYTHON SERVER :: success sent mail
[2023-02-21 11:52:12 +0530] [119061] [INFO] Handling signal: int
[2023-02-21 06:22:12 +0000] [119069] [INFO] Worker exiting (pid: 119069)
[2023-02-21 06:22:12 +0000] [119068] [INFO] Worker exiting (pid: 119068)
Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
    lock.acquire()
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
  File "/mnt/InActive/activeProjects/mailer/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    sys.exit(0)
SystemExit: 0
    sys.exit(0)
SystemExit: 0
[2023-02-21 11:52:12 +0530] [119061] [WARNING] Worker with pid 119068 was terminated due to signal 2
[2023-02-21 11:52:12 +0530] [119061] [WARNING] Worker with pid 119069 was terminated due to signal 2
[2023-02-21 11:52:12 +0530] [119061] [INFO] Shutting down: Master
